### ISSUE TITLE
Placeholders for shorthand notation

### ISSUE THREAD

**Issue by N0tMyFaultOG** [BentoBoxWorld/Level#152] opened 2020-05-06 14:54 UTC
#### Is your feature request related to a problem?

No

#### Describe the solution you'd like us to implement.

Adding a placeholder for the shorthand notation.

#### Describe alternatives you've considered.

/

### Additional context

/

**Comment by johncsuti** [comment] 2020-08-12 13:44
Possible duplicate of #123?

**Comment by Poslovitch** [comment] 2020-08-17 20:23
It is. Closing.

**Closed by Poslovitch** 2020-08-17 20:23 UTC
Labels: enhancement
