### ISSUE TITLE
Placeholder not working

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/Level#82] opened 2019-08-21 01:13 UTC

**Comment by tastybento** [comment] 2019-08-21 21:59
I'm out for a few days so I can't look at this right now, but I will when I get back.

**Comment by Nedjii** [comment] 2019-08-21 23:41
Ok, no problem !

**Comment by tastybento** [comment] 2019-08-22 00:26
I just remembered, there's a SQLite bug in 1.6.0 BentoBox. Download the latest build from the CI server https://ci.codemc.org/job/BentoBoxWorld/job/BentoBox/ to get the fixed version. It'll be 1.7.0_SNAPSHOT, but it's essentially the same.

**Comment by Nedjii** [comment] 2019-08-22 01:37
I'll better wait for the 1.7 to be released as i'm not hurry.

**Comment by Nedjii** [comment] 2019-10-28 21:30
The placeholder doesn't update for some reason, I went from 52 lvl to 1000 and the placeholder keeps telling me 52 when /is level gives me the right number.

**Comment by Nedjii** [comment] 2019-10-28 21:34
It started working again after restart and couldn't reproduce it, will tell here if it happens again.

**Comment by tastybento** [comment] 2019-10-30 00:37
Sounds like a dupe of #94

**Comment by johncsuti** [comment] 2019-11-13 04:02
I had a similar problem it wasn't updating mine was fixed with a server reboot. That should not be needed though.

**Comment by tastybento** [comment] 2020-07-31 02:32
Level has been completely rewritten so this probably doesn't apply. Closing for now.

**Closed by tastybento** 2020-07-31 02:32 UTC
Labels: Under Investigation, bug, duplicate
