### ISSUE TITLE
Problem with implementation

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/Level#188] opened 2020-09-05 22:41 UTC
Hi,
I've problem with using listener from this addon.
```
@EventHandler
	void levelCalculationListener(IslandLevelCalculatedEvent e) {
		System.out.println(e.getLevel());
		System.out.println(e.getInitialLevel());
		ADDON.sendMessageToBungee(new IslandLevelCalcEventInfo(e.getIsland().getUniqueId(), e.getIsland().getOwner(), e.getLevel()-e.getInitialLevel()));
	}
```
e.getLevel() gives normal level, but e.getInitialLevel() always is 0. Am I doing somthing wrong? I need to get players level, but adjusted (without initial level)

```
06.09 00:41:06 [Server] INFO Running PAPER Niepoprawne.
06.09 00:41:06 [Server] INFO BentoBox version: 1.14.2
06.09 00:41:06 [Server] INFO Database: MYSQL
06.09 00:41:06 [Server] INFO Loaded Game Worlds:
06.09 00:41:06 [Server] INFO skyblock (SkyBlock): Overworld, [nether_color]Nether, [end_color]End
06.09 00:41:06 [Server] INFO Loaded Addons:
06.09 00:41:06 [Server] INFO Biomes 1.13.0 (ENABLED)
06.09 00:41:06 [Server] INFO BSkyBlock 1.13.1 (ENABLED)
06.09 00:41:06 [Server] INFO Challenges 0.9.0-SNAPSHOT-#381 (ENABLED)
06.09 00:41:06 [Server] INFO DimensionalTrees 1.6.0-SNAPSHOT (ENABLED)
06.09 00:41:06 [Server] INFO EpicHooks 1.1.0-SNAPSHOT-b5 (ENABLED)
06.09 00:41:06 [Server] INFO Level 2.4.1 (ENABLED)
06.09 00:41:06 [Server] INFO Limits 1.14.0 (ENABLED)
06.09 00:41:06 [Server] INFO SkyblockCore 0.4 (ENABLED)
06.09 00:41:06 [Server] INFO Warps 1.9.7 (ENABLED)
```

**Comment by tastybento** [comment] 2020-09-12 15:48
Possible dupe of #189 .

Please try the latest build and see if that works better for you. The initial level is now subtracted automatically because there is now a setting in config to do that or not do that.

```
# Zero island levels on new island or island reset
# If true, Level will calculate the starter island's level and remove it from any future level calculations.
# If false, the player's starter island and will count towards their level.
# This will reduce CPU if it isn't used.
zero-new-island-levels: false
```

**Closed** 2023-04-24 22:28 UTC
Labels: bug, duplicate
