### ISSUE TITLE
Island name placeholders

### ISSUE THREAD

**Issue by charlyg31** [BentoBoxWorld/Level#211] opened 2021-02-03 20:57 UTC
#### Is your feature request related to a problem?

Add new placeholders for top 10 island,
i need to add %bskyblock_island_name% for top 10 with %bskyblock_island_name_#RANK#%

Thanks.

**Comment by tastybento** [comment] 2021-02-03 22:33
Isn't that already available? https://docs.bentobox.world/en/latest/addons/Level/Placeholders/

**Comment by charlyg31** [comment] 2021-02-04 01:20
it is the name of the owner of the island which is currently displayed, it would be good to be able to put the name of the island which one gives with a / is setname

**Comment by organizatsiya** [comment] 2021-04-01 06:46
Hello,
it already exists: 

`%[gamemode]_island_name% | Name of the island | 1.4.0`

**Comment by charlyg31** [comment] 2021-04-01 07:34
> Hello,
> it already exists:
> 
> `%[gamemode]_island_name% | Name of the island | 1.4.0`

Is not for top 10.

**Comment by tastybento** [comment] 2021-09-06 18:46
Duplicate of #132

**Closed by tastybento** 2021-09-06 18:46 UTC
Labels: enhancement, Under Investigation
