### ISSUE TITLE
Bugged really badly

### ISSUE THREAD

**Issue by ChimpGamer** [BentoBoxWorld/Level#133] opened 2020-02-28 16:02 UTC
#### Describe the bug

Since the beginning I and my players have been experiencing issues with the Levels addon. It started with players having a level 700+ island at the start and we're still having this issue. No idea how it happens. We added the addon before starting the actual game (creating islands, etc) so the addon was not added mid-game. Now we're experiencing more issues. Placeholders are often not working anymore after a restart. /is top being completely empty. I added some screenshots down below.

#### Steps to reproduce the behavior

This is unknown to us so I can't tell. It just happens.

#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/19960733/75564134-dd4bc980-5a4b-11ea-8b38-b5d0912fff71.png)
![image](https://user-images.githubusercontent.com/19960733/75564151-e50b6e00-5a4b-11ea-8d0a-247a18cff103.png)

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.11.1
Database: JSON
Loaded Game Worlds:
skyblock_world (SkyBlock): Overworld, Nether, [end_color]End
Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
Challenges 0.8.0 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
EpicHooks 1.0.0 (ENABLED)
ExtraMobs 1.11.0.2 (ENABLED)
IslandFly 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
Likes 1.7.0 (ENABLED)
Limits 1.9.0 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment] 2020-02-29 02:08
Is a restart a server restart or a reload of some kind, either /bbox reload or plugin reload? I've heard of weird things happening to level if /bbox reload is used.

**Comment by ChimpGamer** [comment] 2020-03-01 12:45
No it happens after every daily restart.

**Comment by tastybento** [comment] 2020-03-01 22:36
Is there anything in the console logs during startup? It looks like the addon is either not able to save to the database or load from the database so it's being zeroed every time.

**Comment by ChimpGamer** [comment] 2020-03-02 15:53
https://pastebin.com/fBsFKuLs

I'm not aware of any error's or warnings on startup by Levels or anything else related to BentoBox.

**Comment by ChimpGamer** [comment] 2020-03-08 11:47
![image](https://user-images.githubusercontent.com/19960733/76162109-7eb4d880-613a-11ea-9ed0-498348e33114.png)

The placeholders area breaking too now. But the /is level command is still working. /is top and /bsb top are throwing errors now
/bsb top
https://pastebin.com/u7fqEt1f

/is top
https://pastebin.com/HycuyWJd

**Comment by tastybento** [comment] 2020-03-08 15:56
Does this occur after a fresh restart?

**Comment by ChimpGamer** [comment] 2020-03-08 17:54
The server restarts everyday.

**Comment by tastybento** [comment] 2020-03-09 02:12
I mean, if you restart the server, are the placeholders fixed?
Also, do you ever use `/bbox reload` or the spigot reload command?

**Comment by ChimpGamer** [comment] 2020-03-09 09:30
After a server restart the placeholders just show empty values if they didn't break. I never do bbox reload or reload since it can cause lots of lag and only causes more issues.

**Comment by tastybento** [comment] 2020-03-10 00:11
The errors you copy and pasted unfortunately do not show anything useful. If I'm to replicate it'd be good to get a copy of your BentoBox folder. Can you zip it up and share or place it somewhere?

**Comment by ChimpGamer** [comment] 2020-03-12 13:59
Sorry I forgot to respond to this. Well you can use the same zip as I've send you in my BentoBox issue.

**Comment by ChimpGamer** [comment] 2020-03-15 13:59
![image](https://user-images.githubusercontent.com/19960733/76702853-82fa6c00-66cd-11ea-9657-3c0c41ce9b51.png)
Sometimes the placeholder also breaks in FeatherBoard (which uses mvdwplaceholderapi)

**Comment by tastybento** [comment] 2020-03-15 23:01
What plugin are you using to display the top ten list? I would like to try it so I can try and replicate this issue.

**Comment by ChimpGamer** [comment] 2020-03-15 23:07
Scoreboard: FeatherBoard
Holograms: CMI

**Comment by tastybento** [comment] 2020-03-15 23:21
Hmm. I don't have those plugins.

So far, I can't seem to break anything. It appears this is a random thing or can you reliably break it?

I need logs to help debug this. When the commands break, can you share the logs? The previous logs you shared 7 days ago unfortunately don't contain useful information. It might be best to just upload the full server log for the day (zip file) so I can look through it. Thanks.

**Comment by ChimpGamer** [comment] 2020-03-15 23:24
[2020-03-15-2.log](https://github.com/BentoBoxWorld/Level/files/4335405/2020-03-15-2.log)

**Comment by tastybento** [comment] 2020-03-15 23:37
Hmm, does that log have an error in it related to the Level commands? I can't see it right now.

A side point, unrelated to this:
```
[05:00:40] [Craft Scheduler Thread - 56/WARN]: [BentoBox] Could not load blueprint bundle 'vip.json' for BSkyBlock.
[05:00:40] [Craft Scheduler Thread - 56/WARN]: [BentoBox] The uniqueId 'vip' is already used by another Blueprint Bundle.
[05:00:40] [Craft Scheduler Thread - 56/WARN]: [BentoBox] This can occur if the Blueprint Bundles' files were manually edited.
[05:00:40] [Craft Scheduler Thread - 56/WARN]: [BentoBox] Please review your Blueprint Bundles' files and make sure their uniqueIds are not in duplicate.
```

Text edit vip.json and change the uniqueId name to be something else (anything unique is okay) otherwise it will not be loaded. Or alternatively, delete it.

**Comment by ChimpGamer** [comment] 2020-03-15 23:40
I got that on my to-do list but I forget it everytime.

**Comment by ChimpGamer** [comment] 2020-03-21 08:11
Any news?

**Comment by tastybento** [comment] 2020-03-21 19:18
The log you gave had no errors in it related to Level. I need logs to debug this. When the commands break, can you share the log?

**Comment by ChimpGamer** [comment] 2020-03-27 02:21
I haven't noticed any errors when using the commands for the last 5 days. But the issue with the placeholders and the is top gui still persists.

**Comment by ChimpGamer** [comment] 2020-03-31 09:42
I finally got the error here: https://pastebin.com/t5etWDwW

**Comment by tastybento** [comment] 2020-03-31 14:44
Is there any more of it? It stopped just before a Caused by line which will tell me what caused the error.

**Comment by ChimpGamer** [comment] 2020-03-31 19:26
No that was all of it




Outlook voor Android downloaden







On Tue, Mar 31, 2020 at 4:44 PM +0200, "tastybento" <notifications@github.com> wrote:















Is there any more of it? It stopped just before a Caused by line which will tell me what caused the error.

**Comment by ChimpGamer** [comment] 2020-04-19 03:32
Any news? It's still broken.

**Comment by tastybento** [comment] 2020-04-22 00:30
Try the latest SNAPSHOT release https://ci.codemc.io/job/BentoBoxWorld/job/Level/ and let me know if it works better for you. Note that this version shifts all the block values into a separate file and out of config.yml. Make a backup of everything beforehand.

**Comment by ChimpGamer** [comment] 2020-04-23 22:59
Still having an empty is top gui and breaking placeholders.

**Comment by tastybento** [comment] 2020-04-23 23:46
Are you using PAPI? That all we support actually now. Anyway, assuming you're using PAPI, run the `/papi parse me %Level_bskyblock_island_level%` and tell me what it says.

**Comment by ChimpGamer** [comment] 2020-04-23 23:49
It tells me the correct island level but that's the not the problem. It's about /is top and the is top placeholders that are breaking. When using MVdW Placeholders for level they were breaking but I'm using PlaceholderAPI for that so that's some kind of work around I already figured out.

**Comment by tastybento** [comment] 2020-04-23 23:51
Okay, so the level placeholders are all completely working.

I assume there is a top ten when you do `/is top`?
What do you see when you do `/papi parse me %Level_bskyblock_top_value_1%` or `/papi parse me %Level_bskyblock_top_name_1%`?

**Comment by ChimpGamer** [comment] 2020-04-23 23:53
The /is top gui is completely empty. Just one row and empty.
/papi parse me %Level_bskyblock_top_value_1% returns 0
/papi parse me %Level_bskyblock_top_name_1% returns an empty line

**Comment by tastybento** [comment] 2020-04-23 23:55
Well, that works too, because if the top ten is empty then the correct placeholders would be 0 and nothing.

Try making some top ten by running `/is level` on an island with some value and then check the placeholders.

**Comment by ChimpGamer** [comment] 2020-04-23 23:57
![2020-04-24_01 56 37](https://user-images.githubusercontent.com/19960733/80160834-e4680180-85ce-11ea-940d-47c9486063c7.png)
The messages are in Dutch but should do the job anyway.

**Comment by tastybento** [comment] 2020-04-24 00:00
So, what you are saying is that you ran level but you did not get into the top ten?

If so, then it's likely that you don't have the top ten permission. It should be given by default, but it is `bskyblock.intopten`. Check you have it specifically. If you don't have it, then your value will not be in the top ten. It's used for admin who don't want to dominate the top ten when they have a huge island.

**Comment by ChimpGamer** [comment] 2020-04-24 00:02
![image](https://user-images.githubusercontent.com/19960733/80161111-9b647d00-85cf-11ea-8ecc-296406b48b6d.png)
I don't have that permission.

**Comment by tastybento** [comment] 2020-04-24 00:19
Okay, that's the problem then. You need that permission to get into the top ten. Give yourself that permission.

**Comment by ChimpGamer** [comment] 2020-04-24 00:23
The other players on my server do have that permission (since it is default). I do not have that permission because I added it as a negative permission to myself. So the top ten should contain players anyway. But I just removed it to test but it's still the same even after executing /is level again.

**Comment by tastybento** [comment] 2020-04-24 00:34
Huh. Okay, I've made a debug build for you to see what is happening there. Please try it and share the console log. Run `/is level` and then `/is top` after you get the result of the island calculation. This is what I got from doing it:

```
[17:31:27 INFO]: tastybento joined the game
[17:31:27 INFO]: tastybento[/127.0.0.1:65375] logged in with entity id 47 at ([bskyblock_world_nether]800.453350536962, 109.0, -795.4364681666626)
[17:31:31 INFO]: tastybento issued server command: /is top
[17:31:35 INFO]: tastybento issued server command: /is level
[17:31:37 INFO]: [BentoBox] DEBUG: Player has permission. Adding tastybento to top ten with score 13
[17:31:40 INFO]: tastybento issued server command: /is top
[17:31:40 INFO]: [BentoBox] DEBUG: Player tastybento has the permission
[17:31:48 INFO]: [BentoBox] Downloading data from GitHub...
[17:31:48 INFO]: [BentoBox] Successfully downloaded data from GitHub.
[17:31:51 INFO]: tastybento lost connection: Disconnected
[17:31:51 INFO]: tastybento left the game
```

[Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/Level/files/4526010/Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip)

**Comment by ChimpGamer** [comment] 2020-04-24 00:41
Alright, I'll try it as soon as the server is empty. Thanks!

**Comment by minhthanh920** [comment] 2020-04-24 14:47
i have the same issue, but /is top just sometimes not working, placeholder working fine. just have issue with /is top, it show nothing.

**Comment by tastybento** [comment] 2020-04-24 17:55
Thanks for your feedback @minhthanh920. Let me hear from @ChimpGamer first on what he sees with the debug build.

**Comment by ChimpGamer** [comment] 2020-04-25 00:04
```
25.04 02:02:34 [Server] INFO ChimpGamer issued server command: /is level
25.04 02:02:37 [Server] INFO [BentoBox] DEBUG: Player has permission. Adding ChimpGamer to top ten with score 742
25.04 02:02:39 [Server] INFO ChimpGamer issued server command: /is top
25.04 02:02:37 [Server] INFO [BentoBox] DEBUG: Player ChimpGamer has the permission
```
That's the result.

**Comment by tastybento** [comment] 2020-04-25 00:05
And what do you see on the screen?

**Comment by ChimpGamer** [comment] 2020-04-25 00:06
An empty is top gui

**Comment by tastybento** [comment] 2020-04-25 00:19
That helps. I think the problem is with the head getter. Please try this version, it doesn't try to get heads from Mojang:
[Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/Level/files/4532068/Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip)

**Comment by ChimpGamer** [comment] 2020-04-25 23:47
That seems to work. The only error I could catch was this one: https://pastebin.com/BtRnr1dR

**Comment by minhthanh920** [comment] 2020-04-26 16:25
https://pastebin.com/qa5KfEv7

**Comment by tastybento** [comment] 2020-04-26 18:39
[Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/Level/files/4536237/Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip)
Thanks for the report guys, we're narrowing in on this. Here's another version. Please try it. The heads will always be Steve right now.

**Comment by ChimpGamer** [comment] 2020-04-29 22:51
![image](https://user-images.githubusercontent.com/19960733/80654478-9d6d8680-8a7c-11ea-8d1f-d0cfc7977fc6.png)
![image](https://user-images.githubusercontent.com/19960733/80654526-bb3aeb80-8a7c-11ea-96dc-5ae09654f7fd.png)
It seems that it broke again.

**Comment by tastybento** [comment] 2020-04-30 02:24
Just mid game, or after a restart?
You are using JSON database right? Check this file:

`/plugins/BentoBox/database/TopTenData/skyblock_world.json`

The name of the file will be your world name.json.

Does this file exist? Does it have anything in it?

I think this might be a permissions issue. It could be that when the bskyblock.intopten perm is checked for players in the top ten, it returns false. I've made a debug build that rips out all the perm checking so there is no removals. Please try it and tell me if you see anything in the console log like:

`[19:21:35 INFO]: [BentoBox] DEBUG: Player LSPvicky does not have the permission bskyblock.intopten`

[Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip](https://github.com/BentoBoxWorld/Level/files/4555792/Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip)

**Comment by ChimpGamer** [comment] 2020-05-04 19:22
`{
  "uniqueId": "skyblock_world",
  "topTen": {}
}`

`[BentoBox] DEBUG: Player LSPvicky does not have the permission bskyblock.intopten`

I don't see those debug messages.

**Comment by tastybento** [comment] 2020-05-05 01:17
Did you try the new build and it still happened?

The content of the file shows that it has nothing in it - no top ten.

**Comment by ChimpGamer** [comment] 2020-05-05 09:34
Yea I did try that new build.

Even when in-game players are in the top ten the file does not contain any player data.

**Comment by minhthanh920** [comment] 2020-05-06 16:51
i trying new build , the same happen still having. The old data bskyblock_world.json deleted when i use Level-2.0.0-SNAPSHOT-b354.

**Comment by tastybento** [comment] 2020-05-06 22:48
@minhthanh920 Can you try the Level-2.0.0-debug-SNAPSHOT-LOCAL.jar.zip file above?

**Comment by tastybento** [comment] 2020-07-31 02:29
Level has been completely rewritten now. Closing.

**Closed by tastybento** 2020-07-31 02:29 UTC
Labels: Under Investigation, bug
