### ISSUE TITLE
/is top getting too many lag(s)

### ISSUE THREAD

**Issue by immakita** [BentoBoxWorld/Level#166] opened 2020-07-08 08:30 UTC
#### Describe the bug

Lag occurs on server when a player uses "/ is top" command

#### Steps to reproduce the behavior

[11:29:31 INFO]: Sunucu PAPER 1.15.2 sürümünde çalışıyor.
[11:29:31 INFO]: BentoBox sürümü: 1.14.0
[11:29:31 INFO]: Database: JSON
[11:29:31 INFO]: Yüklenen oyun dünyaları:
[11:29:31 INFO]: oneblock_world (OneBlock): Overworld
[11:29:31 INFO]: Yüklenen eklentiler:
[11:29:31 INFO]: AOneBlock 1.3.3
[11:29:31 INFO]: Border 1.0.7
[11:29:31 INFO]: Challenges 0.8.2
[11:29:31 INFO]: Chat 1.0.5
[11:29:31 INFO]: Level 2.3.0-SNAPSHOT-b392
[11:29:31 INFO]: Likes 1.7.1
[11:29:31 INFO]: Warps 1.9.7

Use this addons and run is top command

##### Output of `/bbox version` (Mandatory)

```
_______
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

Error code(s)
https://hastebin.com/yusutukopo.md

**Comment by tastybento** [comment] 2020-07-09 01:31
This is due to head getting from Mojang being slow. It's supposed to be async, but it's lagging for some reason. @BONNe has a plan to fix.

**Comment by tastybento** [comment] 2020-07-09 01:32
Duplicate of #164

**Closed by tastybento** 2020-07-09 01:32 UTC
Labels: bug, duplicate
