### ISSUE TITLE
Island Calculation Freeze

### ISSUE THREAD

**Issue by PottersMC** [BentoBoxWorld/Level#172] opened 2020-07-12 10:01 UTC
#### Describe the bug
After using the command "/island level", some islands are not being calculated, freezing the whole Queue. This isn't a time-based thing, as we've given it hours to calculate. There is no error, no message, nothing. After some investigation, we cannot find anything significant at the Island that would cause this.

We run a custom fork of Levels, however it is about 3 commits behind, and simply Queue'd all islands when the server started. This has since been removed, and it appears to occur with a recently compiled, non-edited version too.

#### Steps to reproduce the behavior
It's quite hard to re-produce, but it does appear to affect quite a few players, and at the moment, I'm assuming it's random.

#### Expected behavior
Calculate Islands in a FIFO manner. 

#### Screenshots and videos (Optional)
https://media.discordapp.net/attachments/409775381386887192/731240921022201996/Screenshot_2020-07-10_at_21.10.18.png

This sort of explains the issue, however, this was over the course of a minute. If left, this would have been the case for hours without a restart.

##### Output of `/bbox version` (Mandatory)

```
https://imgur.com/MSX8COM
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment] 2020-07-12 20:44
There is a weird issue with Java 8 where if an error occurs during a CompletableFuture it will just die without any error being generated and it will never complete. Java 8 also has poor async timeout capabilities. I really need Java 9's `orTimeout` feature. Anyway, to solve this we need to narrow down where the failure is happening. To do this, we need to add debug statements in the code and then see where it freezes. That'll help tell us where it happens. Also, this is something I have seen before and I fixed, so make sure you're on the latest version.

If I give you a debug version with console logging, can you run it and see where it freezes? I'd really like to find out where the problem is.

**Comment by PottersMC** [comment] 2020-07-13 10:28
We updated recently to Java 9 and added the timeout (completeOnTimeout), and passed null as the new results to debug a little further.
Well happily use a debug copy, I think you know my discord so feel free to tag me.

**Comment by tastybento** [comment] 2020-07-13 14:12
Let me know if you find anything. 
It'd be useful to have a worlds and database so I can stress test this. Would you be able to zip up yours and share it?

**Comment by tastybento** [comment] 2020-07-13 15:49
By the way are you definitely on the latest version of my code? The reason is because I saw this error a while ago during the chest scanning and it was caused by the chest scanning occurring async. That is, not on the primary thread.￼￼ 
You will see in my code that there are a couple of places where I purposely go back to the main thread, and also where I log if a certain action is occurring not on the primary thread. So those would be areas to check.￼

**Comment by minhthanh920** [comment] 2020-07-16 21:07
i having the same issue, 
include-chests: true ( freeze)
include-chests: false (working well)

i using
paper 1.16.1
BentoBox-1.14.2
Level-2.3.2
Java 11

**Comment by tastybento** [comment] 2020-07-17 22:17
@minhthanh920 When you try with chests included, do you ever see an error in the console `scanChunk not on Primary Thread!`? Could you check your logs?

**Comment by runelynx** [comment] 2020-07-20 02:36
Also experiencing this issue. Players stuck unable to rank up :( 
Can you release the latest version? Latest release is from February with lots of improvements since then

**Comment by runelynx** [comment] 2020-07-20 02:43
Might be of interest; the current level calc is frozen but the "required to next level" does update. So part of the calcs seem to be going through...

![image](https://user-images.githubusercontent.com/5877481/87894609-d88eae80-ca08-11ea-9e8c-a3fc2b38e88f.png)

**Comment by tastybento** [comment] 2020-07-20 05:57
@runelynx I don't think that you reported isn't related to the OP's issue. This ticket is about the level calculation not coming back from a calculation and not about the level not increasing. Please file a new ticket and fill in all the various bits so I know what you're working with. Also, do `/island level (player name)` in the console an you'll get a report that explains exactly why the level is what it is and that may reveal why it's not increasing, e.g., maybe he's hit limits.

**Comment by tastybento** [comment] 2020-07-20 06:07
@PottersMC I did some testing and rigged the server to generate over 4000 islands and had them all sent to the Level addon to calculate. I added a setting in config.yml that enables you to enable concurrent calculations and stress tested all the way up to 4000 in one go. My laptop melted but there were no issues except for super lag because the CPU cores were all maxed out. I did find an issue with `/bbox reload` where old queues were not being cleared and removed, but I could never replicate an issue where the chest calculations ended up on an async thread (yet) which is what was causing the hangs earlier on. So, right now, this *should* work, but, hey, YMMV. So, try Version 2.3.3 and let me know how it goes. I'm closing this issue for now because there isn't anything more I can do unless new issues are found and logs, etc. provided.

**Comment by runelynx** [comment] 2020-07-21 02:42
I set the setting to use all 4 of my CPUs and I still get the same level calculation as shown in my screenshots above.

![image](https://user-images.githubusercontent.com/5877481/88006603-a1380480-cad1-11ea-9073-a02e74d6602b.png)

![image](https://user-images.githubusercontent.com/5877481/88006620-af862080-cad1-11ea-9adf-4b1638840225.png)

[02:37:00] [Server thread/INFO]: Running delayed init tasks
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling game mode addons...
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling BSkyBlock...
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling other addons...
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling Level...
[02:37:00] [Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : acidisland_world
[02:37:00] [Craft Scheduler Thread - 25/INFO]: [Plan] Downloading GeoLite2 requires accepting GeoLite2 EULA - see 'Data_gathering.Accept_GeoLite2_EULA' in the config.
[02:37:00] [Craft Scheduler Thread - 25/WARN]: [Plan] Fallback: using IP2C for Geolocation (doesn't support IPv6).
[02:37:00] [Server thread/INFO]: [BentoBox] [Level] Level hooking into BSkyBlock
[02:37:00] [Craft Scheduler Thread - 24/INFO]: [Plan] You're using the latest version.
[02:37:00] [Craft Scheduler Thread - 30/INFO]: [Vault] Checking for Updates ... 
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling DimensionalTrees...
[02:37:00] [Server thread/INFO]: [BentoBox] Enabling Likes...


[02:38:42] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 8963ms or 179 ticks behind
[02:39:00] [Server thread/INFO]: TPS from last 1m, 5m, 15m: 16.21, 19.11, 19.69
[02:39:03] [Server thread/INFO]: runelynx issued server command: /bsbadmin level iloilop
[02:39:57] [Craft Scheduler Thread - 93/INFO]: [VoidGenerator] VoidGenerator v.1.6.1 is available here: https://www.spigotmc.org/resources/25391/
[02:40:00] [Server thread/INFO]: TPS from last 1m, 5m, 15m: 20.0, 19.11, 19.7
[02:41:00] [Server thread/INFO]: TPS from last 1m, 5m, 15m: 20.0, 19.11, 19.7

**Comment by runelynx** [comment] 2020-07-21 03:05
I tried with chests true and then false again, island calc is the same...  tried changing concurrent up to 100, still the same. It refuses to rethink these levels :(

**Comment by runelynx** [comment] 2020-07-21 03:11
@tastybento Please come back :(

**Comment by BONNe** [comment] 2020-07-21 05:08
Common tasty :D
if you put it with lowercases
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L130
then you need to get value from map also with lowercases :D
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L104

**Comment by tastybento** [comment] 2020-07-21 06:24
Thanks @BONNe 

@runelynx Try the [latest snapshot build](https://ci.codemc.io/job/BentoBoxWorld/job/Level/) and see if that helps you. By the way, this original bug is nothing to do with your issue so it would be better for you to make a new bug report, but since we're here I'll reopen it.

**Comment by BONNe** [comment] 2020-07-21 06:41
I notice that also that the same issue is in:

https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L229
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L240
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L250
https://github.com/BentoBoxWorld/Level/blob/develop/src/main/java/world/bentobox/level/objects/LevelsData.java#L259

**Comment by runelynx** [comment] 2020-07-21 13:22
It's fixed!! Hoorah!!

**Comment by tastybento** [comment] 2020-07-21 14:49
Thanks @BONNe . @runelynx Great news!

**Closed by tastybento** 2020-07-21 14:49 UTC
Labels: Under Investigation, done
