### ISSUE TITLE
Team placeholder

### ISSUE THREAD

**Issue by CubBossa** [BentoBoxWorld/Level#224] opened 2021-06-29 16:33 UTC
### Description
A placeholder like %level_bskyblock_top_name_1%, but instead of showing only the island owner it returns a combined string of all island members (or co-owner?)

#### Describe the solution you'd like us to implement.

%level_bskyblock_top_name_1% -> Cubbossa
%level_bskyblock_top_members_1% -> CubBossa,Julia,Carl
%level_bskyblock_top_owners_1% -> CubBossa,Julia
Something like this, so every player will be represented in leaderbords and not only the islands owner

**Comment by tastybento** [comment] 2021-09-06 18:47
Duplicate of #107

**Comment by tastybento** [comment] 2021-09-06 19:02
Done.

**Closed by tastybento** 2021-09-06 19:02 UTC
Labels: enhancement, Under Investigation
